services:
  frontend:
    build:
      context: ./frontend
      dockerfile: front.Dockerfile
    ports:
      - 8080:80

  backend:
    build:
      context: backend
      dockerfile: back.Dockerfile
    depends_on:
      - mongo
    env_file:
      - ./backend/.env
    ports:
      - 4000:4000
  mongo:
    image: mongo
    restart: always
    env_file:
      - ./mongoDB/.env
    # volumes:
    #   - mongo_storage:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./mongoDB/.env
  minio:
    image: minio/minio:RELEASE.2025-06-13T11-33-47Z-cpuv1
    ports:
      - 9000:9000
      - 9001:9001
    # volumes:
    #   # - ./images:/data
    #   - ./minio/setBucketOpen.sh:/docker-entrypoint-initbucket.d/policy.sh
    env_file:
      - path: minio/.env
        required: true
    command: server /data --console-address ":9001"
  createbuckets:
    image: minio/minio:RELEASE.2025-06-13T11-33-47Z-cpuv1
    depends_on:
      - minio
    # restart: on-failure
    env_file:
      - path: minio/.env
        required: true
    volumes:
      - ./images:/images
      - ./minio/entrypoint.sh:/entrypoint.sh 
    entrypoint: >
      /bin/sh -c "
        chmod +x /entrypoint.sh;
        /bin/sh /entrypoint.sh;
        exit 0;
      "
  
  seed_db:
    image: node:lts-alpine
    depends_on:
      - mongo
    volumes:
      - ./mongoDB/SampleAuctionData.json:/SampleAuctionData.json:ro
      - ./mongoDB/mockUserData.json:/mockUserData.json:ro
      - ./backend/autoSeed.js:/autoSeed.js:ro
      - ./autoDbSeeder:/app/
    env_file:
      - path: ./backend/.env
        required: true
    entrypoint: 
      /bin/sh -c "
      echo 'about to run entrypoint';
      chmod +x /app/entrypoint.sh;
      /bin/sh /app/entrypoint.sh;
      echo 'ran entrypoint';
      exit 0;
      "
